import { ArrowRight, BrainCircuit, BriefcaseBusiness, CalendarDays, Database, Plus, Sparkles } from "lucide-react";
import type { DemoState } from "../../domain/model";
import { LifeRail, ObjectHeader, PrimaryButton, QuietButton, StatusPill, TraceList } from "../../components/ui";
import { researchTrace } from "../../data/demo-content";

export function TodayView({ state, dispatch }: { state: DemoState; dispatch: (action: any) => void }) {
  const hasOpportunity = Boolean(state.opportunity);
  const confirmedCount = state.facts.filter((fact) => fact.status === "confirmed").length;
  return <div className="today-view"><ObjectHeader eyebrow={hasOpportunity ? "你的职业现场" : "上下文已建立"} title={hasOpportunity ? <>今天，先把一个<br /><em>重要机会看清楚。</em></> : <>你的职业现场<br /><em>刚刚建立。</em></>} description={hasOpportunity ? "现在最值得做的不是生成一份更漂亮的材料，而是确认一条会改变判断的未知。" : `${state.userName || "你"}，你已经有一组可以工作的职业事实。下一步，把一个真实机会带进来。`} status={<StatusPill tone="positive">{confirmedCount} 条已确认事实</StatusPill>}><div className="object-links"><button type="button" onClick={() => dispatch({ type: "set-view", view: "profile" })}><Database size={14} />查看职业事实 <ArrowRight size={13} /></button>{hasOpportunity && <button type="button" onClick={() => dispatch({ type: "set-view", view: "opportunity" })}><BriefcaseBusiness size={14} />打开当前机会 <ArrowRight size={13} /></button>}</div></ObjectHeader>{hasOpportunity ? <OpportunityToday state={state} dispatch={dispatch} /> : <EmptyToday dispatch={dispatch} />}</div>;
}

function EmptyToday({ dispatch }: { dispatch: (action: any) => void }) {
  return <div className="empty-today"><section className="empty-primary"><span className="focus-mark"><Plus size={15} /></span><p className="eyebrow">下一件真实的事</p><h2>带入一个你正在考虑的机会</h2><p>职位名称、职责或截图都可以。先把你看到的原始语境保留下来，AI 才能和你的职业事实放在一起看。</p><PrimaryButton onClick={() => dispatch({ type: "load-opportunity" })}>带入第一份机会</PrimaryButton></section><div className="empty-secondary"><div><CalendarDays size={17} /><strong>这里还没有面试</strong><span>当机会产生真实进程后，它会从对象关系中出现。</span></div><div><BrainCircuit size={17} /><strong>AI 还没有开始研究</strong><span>你可以随时让它解释，但不会在没有对象时制造结论。</span></div></div></div>;
}

function OpportunityToday({ state, dispatch }: { state: DemoState; dispatch: (action: any) => void }) {
  const current = state.lifeStage === "discover" ? "先确认职位对象，再开始研究" : state.lifeStage === "research" && state.research.status !== "done" ? "让 AI 展开这份机会的证据" : "确认实际工作方式";
  return <div className="today-object-layout"><section className="today-focus"><span className="focus-mark"><BriefcaseBusiness size={15} /></span><p className="eyebrow">当前机会 · {state.opportunity?.company}</p><h2>{current}</h2><p>{state.lifeStage === "discover" ? "机会对象已经由你确认。下一步是启动一次研究，把职位、职业约束和证据放在同一条可追溯的判断里。" : state.lifeStage === "research" && state.research.status !== "done" ? "AI 会把岗位要求、你的硬约束和公开证据拆开处理，过程中你可以随时介入。" : "官网和职位描述对工作方式的说法存在差异，这会直接影响你的硬约束。"}</p><PrimaryButton onClick={() => state.lifeStage === "discover" ? dispatch({ type: "start-research" }) : state.research.status !== "done" ? dispatch({ type: "start-research" }) : dispatch({ type: "set-life-stage", stage: "communicate" })}>{state.lifeStage === "discover" ? "开始这次研究" : state.research.status !== "done" ? "继续研究" : "准备一次沟通"}</PrimaryButton></section><aside className="today-trace"><div className="trace-heading"><span><Sparkles size={16} />AI 当前任务</span><StatusPill tone={state.research.status === "done" ? "positive" : state.research.status === "running" ? "warning" : "neutral"}>{state.research.status === "done" ? "已完成" : state.research.status === "running" ? "处理中" : "待开始"}</StatusPill></div><TraceList steps={researchTrace} current={state.research.step} status={state.research.status} /></aside><div className="today-rail"><div><h3>这份机会的进程</h3><span>{state.lifeStage === "discover" ? "对象已确认 · 等待研究" : "继续沿着对象关系前进"}</span></div><LifeRail current={state.lifeStage} onStage={(stage) => dispatch({ type: "set-life-stage", stage })} /></div></div>;
}
