import { ArrowRight, BrainCircuit, CheckCircle2, HelpCircle, MessageCircleQuestion, Sparkles } from "lucide-react";
import type { DemoState, EvidenceItem, LifeStage } from "../../domain/model";
import { demoEvidence, researchTrace } from "../../data/demo-content";
import { EvidenceRow, LifeRail, ObjectHeader, PrimaryButton, QuietButton, StatusPill, TraceList } from "../../components/ui";

export function OpportunityView({ state, dispatch }: { state: DemoState; dispatch: (action: any) => void }) {
  const opportunity = state.opportunity!;
  const evidence = state.research.evidence.length ? state.research.evidence : demoEvidence;
  const selected = evidence.find((item) => item.id === state.selectedEvidenceId) ?? evidence[0];
  const isResearching = state.lifeStage === "research";
  return <div className="feature-view"><ObjectHeader eyebrow={`当前机会 · ${stageLabel(state.lifeStage)}`} title={<>{opportunity.company}<br /><em>{opportunity.role}</em></>} description={`${opportunity.salary} · ${opportunity.location} · ${opportunity.direction}`} status={<StatusPill tone={state.decision ? "positive" : "warning"}>{state.decision ? decisionLabel(state.decision) : "建议谨慎投入"}</StatusPill>}><div className="object-links"><button type="button" onClick={() => dispatch({ type: "set-view", view: "profile" })}><CheckCircle2 size={14} />参与判断的职业事实 <ArrowRight size={13} /></button><button type="button" onClick={() => dispatch({ type: "set-view", view: "today" })}><Sparkles size={14} />回到今天 <ArrowRight size={13} /></button></div></ObjectHeader><LifeRail current={state.lifeStage} onStage={(stage) => dispatch({ type: "set-life-stage", stage })} />{isResearching ? <ResearchStage state={state} selected={selected} evidence={evidence} dispatch={dispatch} /> : <LifecycleStage state={state} dispatch={dispatch} />}</div>;
}

function ResearchStage({ state, selected, evidence, dispatch }: { state: DemoState; selected: EvidenceItem; evidence: EvidenceItem[]; dispatch: (action: any) => void }) {
  return <div className="opportunity-workspace"><section className="research-main"><div className="conclusion-block"><div><p className="eyebrow"><span className="focus-dot" />当前建议</p><h2>能力匹配，但现实条件仍需确认</h2><p>岗位方向与你的复杂前端和工程化经历一致。建议先确认实际工作方式，再决定是否投入完整申请。</p></div><strong className="conclusion-word">谨慎<br />投入</strong></div><div className="analysis-surface compact"><div className="trace-heading"><span><BrainCircuit size={16} />研究任务</span><StatusPill tone={state.research.status === "done" ? "positive" : state.research.status === "running" ? "warning" : "neutral"}>{state.research.status === "done" ? "已完成" : state.research.status === "running" ? "处理中" : "待开始"}</StatusPill></div><TraceList steps={researchTrace} current={state.research.step} status={state.research.status} />{state.research.status !== "done" && <PrimaryButton onClick={() => state.research.status === "running" ? dispatch({ type: "advance-research" }) : dispatch({ type: "start-research" })}>{state.research.status === "running" ? "继续下一步" : "开始研究"}</PrimaryButton>}</div><section className="evidence-section"><div className="section-heading"><div><p className="eyebrow">依据对象</p><h2>证据与未知</h2></div><span>{evidence.length} 条来源</span></div><div className="evidence-layout"><div className="evidence-list">{evidence.map((item) => <EvidenceRow key={item.id} evidence={item} selected={item.id === selected.id} onClick={() => dispatch({ type: "set-evidence", id: item.id })} />)}</div><div className="evidence-detail"><StatusPill tone={selected.tone === "support" ? "positive" : selected.tone === "neutral" ? "info" : "warning"}>{toneLabel(selected.tone)}</StatusPill><h3>{selected.title}</h3><p>{selected.excerpt}</p><div className="impact-line"><span>影响判断</span>{selected.impact}</div><div className="linked-question"><HelpCircle size={15} /><span>它连接到一个未知：<strong>团队实际工作方式</strong></span></div></div></div></section></section><aside className="opportunity-side"><section className="next-object"><p className="eyebrow"><span className="focus-dot" />下一动作</p><h3>问清实际工作方式</h3><p>这不是自动发送的消息。AI 可以帮你准备，发送、语气和时机仍由你控制。</p><PrimaryButton onClick={() => dispatch({ type: "set-life-stage", stage: "communicate" })}>准备沟通草稿</PrimaryButton></section><section className="decision-object"><p className="eyebrow"><MessageCircleQuestion size={14} />用户决定</p><h3>{state.decision ? `已选择${decisionLabel(state.decision)}` : "这份机会值得投入多少？"}</h3><p>{state.decision ? "你的决定和系统建议分开保存，之后可以在结果中回看。" : "理解建议之后，由你选择申请、暂缓或放弃。"}</p><div className="decision-actions"><button type="button" onClick={() => dispatch({ type: "set-decision", decision: "apply" })}>申请</button><button type="button" onClick={() => dispatch({ type: "set-decision", decision: "hold" })}>暂缓</button><button type="button" onClick={() => dispatch({ type: "set-decision", decision: "decline" })}>放弃</button></div></section></aside></div>;
}

function LifecycleStage({ state, dispatch }: { state: DemoState; dispatch: (action: any) => void }) {
  const stage = state.lifeStage;
  const content: Record<string, { title: string; description: string; items: string[]; action: string }> = {
    discover: { title: "机会对象已经确认", description: "原始职位材料、来源和当前职业方向已经连接。下一步启动研究，让证据和未知项进入这个对象。", items: ["职位原文与来源已保留", "公司、岗位和方向已经识别", "研究任务还没有开始"], action: "开始这次研究" },
    communicate: { title: "把关键问题问得自然", description: "消息只会留在草稿里。你可以修改后，亲自在招聘平台发送。", items: ["团队实际每周到岗与远程规则", "岗位是否承担人员绩效管理", "当前最重要的技术目标与授权范围"], action: "生成沟通草稿" },
    applied: { title: "申请进入你的记录", description: "保存投递渠道、时间和当时使用的材料，之后才知道哪些判断得到了现实回应。", items: ["申请渠道：招聘平台", "申请材料：岗位定制版简历", "待跟进：3 个工作日后回看"], action: "记录一次跟进" },
    offer: { title: "把 Offer 放回你的生活里比较", description: "薪资只是一个字段。职级、工作方式、成长空间和机会成本要放在同一张判断里。", items: ["35-45K · 14 薪", "每周远程两天（待确认）", "平台能力建设方向"], action: "添加 Offer 条款" },
    outcome: { title: "结果是新的证据", description: "记录发生了什么，哪些地方和原来的判断不同，再决定是否调整方向或表达。", items: ["当前状态：等待真实结果", "复盘问题：哪条证据最有价值？", "策略回写：等待你的确认"], action: "开始一次复盘" },
  };
  const current = content[stage] ?? { title: "面试是一次双向判断", description: "围绕当前岗位准备，不把通用题库当成你的经历。", items: ["准备 3 个架构经历切入点", "记录对方提到的团队与授权", "面试后补充真实反馈"], action: "打开面试准备" };
  return <div className="lifecycle-object"><section><p className="eyebrow">{stageLabel(stage)}</p><h2>{current.title}</h2><p>{current.description}</p><div className="object-list">{current.items.map((item) => <div key={item}><CheckCircle2 size={15} /><span>{item}</span></div>)}</div><PrimaryButton onClick={() => stage === "interview" ? dispatch({ type: "set-view", view: "interview" }) : stage === "discover" ? dispatch({ type: "start-research" }) : dispatch({ type: "set-lifecycle-note", note: `${current.action}已加入当前旅程，等待你的审核。` })}>{stage === "discover" ? current.action : state.lifecycleNote ?? current.action}</PrimaryButton></section><aside className="lifecycle-note"><Sparkles size={16} /><strong>这一步会留下什么</strong><p>每次外部行动都会和当前机会、当时建议及你的决定连接起来。</p></aside></div>;
}

function stageLabel(stage: LifeStage) { return ({ discover: "带入", research: "研究", communicate: "沟通", applied: "申请", interview: "面试", offer: "Offer", outcome: "结果" })[stage]; }
function decisionLabel(decision: Exclude<DemoState["decision"], null>) { return decision === "apply" ? "申请" : decision === "hold" ? "暂缓" : "放弃"; }
function toneLabel(tone: EvidenceItem["tone"]) { return tone === "support" ? "支持判断" : tone === "risk" ? "风险信号" : tone === "conflict" ? "来源冲突" : "背景事实"; }
