import { ArrowRight, CalendarDays, CheckCircle2, Sparkles } from "lucide-react";
import type { Dispatch } from "react";
import type { AppAction } from "../../app/state";
import type { DemoState } from "../../domain/model";
import { ObjectHeader, PrimaryButton, ReturnToday, StatusPill } from "../../components/ui";

export function InterviewView({ state, dispatch }: { state: DemoState; dispatch: Dispatch<AppAction> }) {
  const event = state.interviewEvent;
  if (!event) return null;
  const recorded = event.status === "recorded";
  return <div className="feature-view"><ReturnToday onClick={() => dispatch({ type: "set-view", view: "today" })} /><ObjectHeader eyebrow={`关联事件 · ${event.scheduledAt}`} title={<>把一次面试，<br /><em>变成下一次的证据。</em></>} description="准备要验证的未知，记录真实回应，再由你决定这些信息如何改变当前机会。" status={<StatusPill tone={recorded ? "positive" : "info"}>{recorded ? "已记录" : "待发生"}</StatusPill>}><div className="object-links"><button type="button" onClick={() => dispatch({ type: "set-view", view: "opportunity" })}><CalendarDays size={14} />回到当前机会 <ArrowRight size={13} /></button></div></ObjectHeader><div className="interview-layout"><section className="interview-event"><div className="event-summary"><span className="calendar-icon"><CalendarDays size={19} /></span><div><p className="eyebrow">{state.opportunity?.company} · {event.title}</p><h2>{event.scheduledAt}</h2><p>{event.purpose}</p></div></div><div className="interview-prompts">{event.prompts.map((prompt) => <div key={prompt}><CheckCircle2 size={14} /><span>{prompt}</span></div>)}</div>{recorded ? <div className="interview-result"><span>你记录的现场信息</span><p>{event.notes}</p><div className="interview-result-actions"><PrimaryButton onClick={() => dispatch({ type: "create-offer" })}>记录收到 Offer</PrimaryButton><button type="button" onClick={() => dispatch({ type: "create-outcome" })}>记录未继续并复盘</button></div></div> : <div className="interview-note-form"><label htmlFor="interview-note">面试后，你会把什么事实带回来？</label><textarea id="interview-note" defaultValue="对方确认岗位有架构决策空间，但需要长期高强度到岗；正式人员管理边界仍不清楚。" /><PrimaryButton onClick={() => dispatch({ type: "record-interview", notes: "对方确认岗位有架构决策空间，但需要长期高强度到岗；正式人员管理边界仍不清楚。" })}>保存这次面试记录</PrimaryButton></div>}</section><aside className="interview-aside"><div className="interview-principle"><Sparkles size={17} /><h3>这不是成败评分</h3><p>事件的价值在于产生新的可验证信息，而不是给你贴上“通过”或“失败”的标签。</p></div><div className="interview-timeline"><h3>这次事件连接什么</h3><div><CheckCircle2 size={14} /><span>原机会与研究建议</span></div><div><CheckCircle2 size={14} /><span>团队授权与工作方式未知</span></div><div><CheckCircle2 size={14} /><span>之后的 Offer 或结果复盘</span></div></div></aside></div></div>;
}
